<?php
include_once('Pesapal_OAuth.php');

//pesapal params
$token = $params = NULL;

$consumer_key = $pesapal_consumer_key;

$consumer_secret = $pesapal_consumer_secret;

$signature_method = new OAuthSignatureMethod_HMAC_SHA1();

if($pesapal_demo) { // testing payment
	$iframelink = 'https://demo.pesapal.com/api/PostPesapalDirectOrderV4';
} else { // real payment
	$iframelink = 'https://www.pesapal.com/API/PostPesapalDirectOrderV4';
}

//get form details
$amount = $amount;
$amount = number_format($amount, 2);//format amount to 2 decimal places

$desc = "static desc";
$type = "MERCHANT"; //default value = MERCHANT
$reference = $reference;//unique order id of the transaction, generated by merchant
$email = $email;

$callback_url = base_url().'accounting/payment/pesapal_response/'.$reference; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchemainstance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" Email=\"".$email."\" xmlns=\"http://www.pesapal.com\" />";

$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);
$iframe_src->sign_request($signature_method, $consumer, $token);

//display pesapal - iframe and pass iframe_src
?>
<iframe src="<?php echo $iframe_src;?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
	<p>Browser unable to load iFrame</p>
</iframe>
